name: fbthrift
on:
  workflow_dispatch:

jobs:
  build_fbthrift:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set SELinux context for artifacts
        run: sudo chcon -R -u system_u -t container_file_t ./artifacts

      - name: Build fbthrift
        run: ./scripts/build-fbthrift.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: artifacts/x86_64/fbthrift-*.tar.xz
