name: fbthrift
on:
  workflow_dispatch:
  schedule:
    - cron: "10 16 * * 1,4"

permissions:
  contents: read

jobs:
  fbthrift-el10-x86_64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Build fbthrift tarball
        run: ./scripts/build-fbthrift.sh

      - name: Test fbthrift tarball
        run: ./scripts/test-fbthrift.sh

      - name: Get artifact name
        id: artifact_name
        run: |
          set -e

          name="$(basename "$(find ./artifacts -name '*.tar.xz' | head -n1)")"
          name="${name%.tar.xz}"
          echo "name=$name" >>"$GITHUB_OUTPUT"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact_name.outputs.name }}
          path: artifacts/fbthrift-*.tar.xz
