name: fbthrift
on:
  workflow_dispatch:

jobs:
  fbthrift-x86_64-el10:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Build fbthrift
        run: ./scripts/build-fbthrift.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: artifacts/x86_64/fbthrift-*.tar.xz
