name: fbthrift
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fbthrift-el10-x86_64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Build fbthrift tarball
        run: ./scripts/build-fbthrift.sh

      - name: Test fbthrift tarball
        run: ./scripts/test-fbthrift.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: x86_64
          path: artifacts/x86_64/fbthrift-*.tar.xz
