name: sapling
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sapling-el10-x86_64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Fetch fbthrift
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./scripts/fetch-fbthrift.sh

      - name: Build sapling RPM
        run: ./scripts/build-sapling.sh

      - name: Test sapling RPM
        run: ./scripts/test-sapling.sh

      - name: Get artifact name
        id: artifact_name
        run: |
          name="$(basename "$(find ./artifacts -name '*.rpm' | head -n1)")"
          name="${name%.rpm}"
          echo "name=$name" >>"$GITHUB_OUTPUT"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact_name.outputs.name }}
          path: artifacts/sapling-*.rpm
