name: test
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-passing-output:
    runs-on: ubuntu-latest

    steps:
      - name: Get artifact name
        id: artifact_name
        run: |
          name="$(basename "$(find /usr/lib -name 'netifaces.*.so' | head -n1)")"
          name="${name%.rpm}"
          echo "name=$name" >>"$GITHUB_OUTPUT"

      - name: Use output
        run: |
          echo "Got output: ${{ steps.artifact_name.outputs.name }}"
